# Generated by Django 5.1.7 on 2025-03-18 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=50)),
                ('CNPJ', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(blank=True, max_length=50)),
                ('preco_padrao', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('descricao_produto', models.TextField(blank=True)),
                ('data_validade_produto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateField(auto_now_add=True)),
                ('status_pedido', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('cartao', 'Cartão'), ('boleto', 'Boleto'), ('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência')], default='cartao', max_length=20)),
                ('status_pagamento', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id_tabela', models.AutoField(primary_key=True, serialize=False)),
                ('preco_personalizado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('status_venda', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.cliente')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.pagamento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField(blank=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.venda')),
            ],
        ),
    ]
