# Generated by Django 5.1.7 on 2025-04-22 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='sistema_pagamentos.produto'),
        ),
    ]
