# Generated by Django 5.1.7 on 2025-03-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pagamentos', '0002_alter_cliente_cnpj_alter_itemvenda_preco_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='metodo_pagamento',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, null=True),
        ),
    ]
