# Generated by Django 5.1.7 on 2025-03-18 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pagamentos', '0004_pagamento_metodo_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.CharField(choices=[('naorealizado', 'Não realizado'), ('pendente', 'Pendente'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='naorealizado', max_length=20),
        ),
    ]
