# Generated by Django 5.1.7 on 2025-03-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pagamentos', '0005_pedido_produto_alter_pedido_status_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='quantidade_pedido',
            field=models.IntegerField(default=0),
        ),
    ]
