# Generated by Django 5.1.7 on 2025-03-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pagamentos', '0008_alter_pagamento_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='quantidade_parcelas',
            field=models.CharField(choices=[('avista', 'Avista'), ('duas', '2x'), ('tres', '3x'), ('quatro', '4x'), ('cinco', '5x'), ('seis', '6x'), ('sete', '7x'), ('oito', '8x'), ('nove', '9x'), ('dez', '10x'), ('onze', '11x'), ('doze', '12x')], default='avista', max_length=10),
        ),
    ]
