# Generated by Django 5.1.7 on 2025-03-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pagamentos', '0009_alter_pagamento_quantidade_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CNPJ',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
