# Generated by Django 5.1.7 on 2025-03-19 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pagamentos', '0010_alter_cliente_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCompra',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.venda')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemVenda',
        ),
    ]
