# Generated by Django 5.1.7 on 2025-03-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pagamentos', '0011_historicocompra_delete_itemvenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocompra',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='historicocompra',
            name='quantidade',
        ),
    ]
