# Generated by Django 5.1.7 on 2025-03-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pagamentos', '0012_remove_historicocompra_preco_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocompra',
            name='produto',
        ),
    ]
