# Generated by Django 5.1.7 on 2025-03-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pagamentos', '0014_remove_historicocompra_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='CNPJ',
        ),
        migrations.DeleteModel(
            name='TabelaPreco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
