# Generated by Django 5.1.7 on 2025-03-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pagamentos', '0015_remove_cliente_cnpj_delete_tabelapreco_cliente_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='pedido',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_pagamentos.pedido'),
        ),
        migrations.DeleteModel(
            name='HistoricoCompra',
        ),
    ]
